Revert "Removed unused includes"
This reverts commit c9eb8f82e9febeb634a23bec6aeea915eb25fe26.

The change caused "implicit declaration" warning and actual segfault.

```
/tmp/ruby/v2/src/trunk-gc-asserts/enc/gb2312.c: In function ‘Init_gb2312’:
/tmp/ruby/v2/src/trunk-gc-asserts/enc/gb2312.c:6:31: warning: implicit declaration of function ‘rb_enc_find’ [-Wimplicit-function-declaration]
     rb_enc_register("GB2312", rb_enc_find("EUC-KR"));
                               ^~~~~~~~~~~
/tmp/ruby/v2/src/trunk-gc-asserts/enc/gb2312.c:6:31: warning: passing argument 2 of ‘rb_enc_register’ makes pointer from integer without a cast [-Wint-conversion]
<command-line>:0:19: note: expected ‘OnigEncoding {aka const struct OnigEncodingTypeST *}’ but argument is of type ‘int’
/tmp/ruby/v2/src/trunk-gc-asserts/regenc.h:231:12: note: in expansion of macro ‘ONIG_ENC_REGISTER’
 extern int ONIG_ENC_REGISTER(const char *, OnigEncoding);
            ^~~~~~~~~~~~~~~~~
```